
name: Generate CV Files
on: [workflow_dispatch]
jobs:
  Update_README_MD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - run: python --version
      - name: Generate README.MD
        run: python src/json2md.py
      - name: Push changes to repository
        run: |
          git config --global user.name "Actions bot"
          git config --global user.email "bot@mail.com"
          git pull origin ${{ github.ref }}
          git add -A
          git commit -m "[Update_README_MD]: update README.md"
          git push