
name: Generate CV Files
on:
  pull_request:
    branches:
      - main
jobs:
  Update_README_MD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - run: python --version
      - name: Generate README.MD
        run: python src/json2md.py
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
