name: Generate CV Files
on: push
jobs:
  Update_README_MD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - run: python --version
      - name: Generate README.MD
        run: python src/json2md.py
      - name: Push changes to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Autogenerate README.md"
          git push
